// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamGames.Models;

#nullable disable

namespace SteamGames.Migrations
{
    [DbContext(typeof(UserCredentialsContext))]
    partial class UserCredentialsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SteamGames.Models.UserCredentials", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("email");

                    b.ToTable("UserCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
